// data.jsx — recipes seed data

const CATEGORIES = [
  { id: 'all',       label: 'הכל',        emoji: '🍽️' },
  { id: 'mains',     label: 'עיקריות',     emoji: '🥘' },
  { id: 'salads',    label: 'סלטים',       emoji: '🥗' },
  { id: 'desserts',  label: 'קינוחים',      emoji: '🍰' },
  { id: 'breakfast', label: 'ארוחת בוקר',  emoji: '🥐' },
  { id: 'bakery',    label: 'מאפים',       emoji: '🍞' },
];

// Palette per recipe. Each has a primary block color + a softer secondary
// for the detail view body section.
const PALETTES = {
  yellow:   { bg: '#ffd255', bg2: '#fff1c2', ink: '#3a2a0a', tag: '#ffefb8', accent: '#c98a14' },
  sky:      { bg: '#8fd6e7', bg2: '#dbf3f8', ink: '#0f3641', tag: '#cdedf3', accent: '#1d7d92' },
  pink:     { bg: '#f7a8b8', bg2: '#ffe2e8', ink: '#3a1622', tag: '#ffd2db', accent: '#b3445a' },
  mint:     { bg: '#9adfb1', bg2: '#dff3e6', ink: '#0e3b25', tag: '#c8ecd4', accent: '#2c8a52' },
  lavender: { bg: '#c9b8e8', bg2: '#e9e0f8', ink: '#2a1e4a', tag: '#dccdf3', accent: '#6b50a6' },
  peach:    { bg: '#ffb494', bg2: '#ffdfcd', ink: '#3d1a0a', tag: '#ffd2bd', accent: '#c2552a' },
};

// gallery: array of slot suffixes. We pre-seed a primary slot ('main') + a
// couple of empty additional slots so the user can drop more photos and
// they persist via the <image-slot> component.
const defaultGallery = () => ['main', 'g1', 'g2'];

const RECIPES = [
  {
    id: 'cheesecake',
    title: 'עוגת גבינה לימון',
    subtitle: 'קינוח קליל וחמצמץ',
    description: 'עוגת גבינה חמצמצה ועדינה שיושבת על בסיס פירורי שקדים ועוגיות, מצופה בקרם לימון מבריק. מושלמת לארוחה משפחתית בסוף שבוע.',
    palette: 'yellow',
    category: 'desserts',
    cuisine: 'אירופאית',
    time: 90, prepTime: 30, cookTime: 60, servings: 8, level: 'בינוני',
    favorite: true,
    notes: 'במקרר העוגה משתפרת אחרי לילה. אפשר להוסיף קונפיטורת פטל מתחת לקרם.',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '110 גרם', name: 'עוגיות פתי-בר', icon: 'bread' },
      { qty: '50 גרם',  name: 'חמאה מומסת',    icon: 'dairy' },
      { qty: '25 גרם',  name: 'סוכר חום בהיר', icon: 'sweet' },
      { qty: '350 גרם', name: 'גבינת מסקרפונה', icon: 'cheese' },
      { qty: '75 גרם',  name: 'סוכר לבן',       icon: 'sweet' },
      { qty: '200 גרם', name: 'שמנת מתוקה',     icon: 'dairy' },
      { qty: '2 כפות',  name: 'מיץ לימון טרי',  icon: 'fruit' },
      { qty: '1 כף',    name: 'גרידת לימון',    icon: 'fruit' },
    ],
    steps: [
      { title: 'מכינים את הבסיס', body: 'טוחנים את העוגיות לפירורים, מערבבים עם החמאה המומסת והסוכר החום. לוחצים לתחתית תבנית מקפיץ ומקפיאים ל-15 דקות.' },
      { title: 'מערבלים את הגבינה', body: 'במיקסר מקציפים את המסקרפונה עם הסוכר עד לקבלת תערובת חלקה ואחידה.' },
      { title: 'מוסיפים שמנת', body: 'בקערה נפרדת מקציפים את השמנת לקצף יציב ומקפלים בעדינות לתערובת הגבינה יחד עם מיץ וגרידת הלימון.' },
      { title: 'יוצקים ומקררים', body: 'יוצקים את הקרם על הבסיס המוקפא, מחליקים את הפני העוגה ומעבירים למקרר ללילה שלם.' },
      { title: 'מקשטים ומגישים', body: 'לפני ההגשה מקשטים בפרוסות לימון דקות, עלי מנטה וסירופ לימון. חותכים בסכין רטובה לפרוסות נקיות.' },
    ],
  },
  {
    id: 'shakshuka',
    title: 'שקשוקה ירושלמית',
    subtitle: 'ארוחת בוקר חמה ומתובלת',
    description: 'שקשוקה אדומה וחריפה עם רוטב עגבניות סמיך, פלפלים אדומים מתוקים ותיבול עשיר. מגישים ישר מהמחבת עם לחם טרי וגבינה בולגרית.',
    palette: 'peach',
    category: 'breakfast',
    cuisine: 'מזרח-תיכונית',
    time: 35, prepTime: 10, cookTime: 25, servings: 4, level: 'קל',
    favorite: false,
    notes: '',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '6 יח׳',    name: 'ביצים גדולות',           icon: 'egg' },
      { qty: '4 יח׳',    name: 'עגבניות בשלות',          icon: 'veg' },
      { qty: '1 יח׳',    name: 'בצל סגול קצוץ',          icon: 'veg' },
      { qty: '2 יח׳',    name: 'פלפלים אדומים',          icon: 'veg' },
      { qty: '4 שיני',   name: 'שום כתוש',                icon: 'veg' },
      { qty: '2 כפיות',  name: 'פפריקה מתוקה',            icon: 'spice' },
      { qty: '1 כפית',   name: 'כמון טחון',                icon: 'spice' },
      { qty: 'לפי טעם',  name: 'מלח, פלפל, פטרוזיליה',   icon: 'herb' },
    ],
    steps: [
      { title: 'מטגנים את הירקות', body: 'במחבת רחבה מחממים שמן זית, מוסיפים בצל ופלפלים ומטגנים כ-7 דקות עד שמתרככים.' },
      { title: 'מוסיפים תבלינים', body: 'מוסיפים שום, פפריקה, כמון ומערבבים דקה נוספת עד שעולה ניחוח עשיר.' },
      { title: 'רוטב עגבניות', body: 'מוסיפים עגבניות חתוכות, מלח ופלפל. מבשלים על אש בינונית 15 דקות עד שהרוטב סמיך.' },
      { title: 'שוברים ביצים', body: 'יוצרים גומות ברוטב, שוברים פנימה ביצה לכל גומה ומכסים. מבשלים 5–7 דקות עד שהחלבון נקרש.' },
      { title: 'מגישים', body: 'מפזרים פטרוזיליה קצוצה, מגישים ישר מהמחבת עם לחם טרי וגבינה בולגרית מפוררת.' },
    ],
  },
  {
    id: 'macaroons',
    title: 'מקרונים צרפתיים',
    subtitle: 'עוגיות עדינות בשלל צבעים',
    description: 'רכים מבפנים, פריכים וזהובים מבחוץ — מקרונים צבעוניים במגוון טעמים מלאים בקרם מסקרפונה אווירי. אומנות בכל ביס.',
    palette: 'sky',
    category: 'desserts',
    cuisine: 'צרפתית',
    time: 120, prepTime: 60, cookTime: 60, servings: 24, level: 'מתקדם',
    favorite: true,
    notes: '',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '150 גרם', name: 'אבקת שקדים',          icon: 'nuts' },
      { qty: '150 גרם', name: 'אבקת סוכר',            icon: 'sweet' },
      { qty: '55 גרם',  name: 'חלבון ביצה (לאיטלקי)', icon: 'egg' },
      { qty: '150 גרם', name: 'סוכר לבן',             icon: 'sweet' },
      { qty: '50 מ"ל',  name: 'מים',                  icon: 'drop' },
      { qty: '55 גרם',  name: 'חלבון נוסף',           icon: 'egg' },
      { qty: 'לפי בחירה', name: 'צבעי מאכל ג׳ל',     icon: 'chef' },
    ],
    steps: [
      { title: 'מנפים', body: 'מנפים יחד אבקת שקדים ואבקת סוכר 2–3 פעמים לתערובת אחידה לחלוטין.' },
      { title: 'מקרונאז׳', body: 'מערבבים חלבון אחד עם אבקת השקדים, מכינים סירופ סוכר ב-118°C ומקציפים לחלבון השני למרנג איטלקי.' },
      { title: 'מקפלים', body: 'מקפלים את שני התערובות עד שהבלילה זורמת בסרט רציף — לא יותר, לא פחות.' },
      { title: 'מזלפים ומייבשים', body: 'מזלפים עיגולים על נייר אפייה, טופחים בתבנית להוצאת אוויר ומייבשים 30 דקות עד שנוצר קרום.' },
      { title: 'אופים וממלאים', body: 'אופים ב-150°C כ-14 דקות עד שמופיעות "רגליים". מצננים ומדביקים זוגות עם קרם מסקרפונה.' },
    ],
  },
  {
    id: 'greek-salad',
    title: 'סלט יווני קלאסי',
    subtitle: 'רענן, חמצמץ וים-תיכוני',
    description: 'הקלאסיקה היוונית — עגבניות עסיסיות, מלפפונים פריכים, בצל אדום, זיתי קלמטה וקובייה גדולה של פטה. שמן זית טוב ועלי אורגנו טריים.',
    palette: 'mint',
    category: 'salads',
    cuisine: 'יוונית',
    time: 15, prepTime: 15, cookTime: 0, servings: 4, level: 'קל',
    favorite: false,
    notes: '',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '4 יח׳',    name: 'עגבניות בשלות',           icon: 'veg' },
      { qty: '2 יח׳',    name: 'מלפפונים',                 icon: 'veg' },
      { qty: '1 יח׳',    name: 'בצל סגול',                 icon: 'veg' },
      { qty: '200 גרם',  name: 'גבינת פטה',                icon: 'cheese' },
      { qty: '100 גרם',  name: 'זיתי קלמטה',                icon: 'fruit' },
      { qty: '3 כפות',   name: 'שמן זית כתית מעולה',       icon: 'drop' },
      { qty: '1 כפית',   name: 'אורגנו יבש',                icon: 'herb' },
      { qty: 'לפי טעם',  name: 'מלח, פלפל שחור',           icon: 'spice' },
    ],
    steps: [
      { title: 'חותכים גס', body: 'חותכים עגבניות ומלפפונים לקוביות גדולות, בצל לטבעות דקות.' },
      { title: 'מערבבים', body: 'בקערת הגשה רחבה מערבבים את הירקות עם הזיתים.' },
      { title: 'מוסיפים פטה', body: 'מניחים קובייה גדולה של פטה במרכז — לא מפוררים!' },
      { title: 'מתבלים', body: 'יוצקים מעל שמן זית מעולה, מפזרים אורגנו, מלח ופלפל טחון טרי.' },
    ],
  },
  {
    id: 'mushroom-pasta',
    title: 'פסטה ברוטב פטריות',
    subtitle: 'קרמית, ריחנית ומנחמת',
    description: 'פטוצ׳יני ברוטב פטריות שמפיניון וטרי ניצנים בקרם שמנת עשיר, יין לבן, שום ופרמזן. מנת ערב שעוטפת אותך בכל ביס.',
    palette: 'lavender',
    category: 'mains',
    cuisine: 'איטלקית',
    time: 30, prepTime: 10, cookTime: 20, servings: 4, level: 'קל',
    favorite: true,
    notes: '',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '400 גרם',  name: 'פטוצ׳יני יבש',     icon: 'grain' },
      { qty: '500 גרם',  name: 'פטריות מעורבות',   icon: 'veg' },
      { qty: '3 שיני',   name: 'שום קצוץ',          icon: 'veg' },
      { qty: '100 מ"ל',  name: 'יין לבן יבש',       icon: 'bottle' },
      { qty: '250 מ"ל',  name: 'שמנת מתוקה',        icon: 'dairy' },
      { qty: '80 גרם',   name: 'פרמזן מגורר',       icon: 'cheese' },
      { qty: '30 גרם',   name: 'חמאה',              icon: 'dairy' },
      { qty: 'לפי טעם',  name: 'פטרוזיליה, מלח, פלפל', icon: 'herb' },
    ],
    steps: [
      { title: 'מבשלים פסטה', body: 'מרתיחים סיר מים גדול עם המון מלח. מבשלים את הפסטה אל-דנטה לפי ההוראות, שומרים כוס ממי הבישול.' },
      { title: 'משחימים פטריות', body: 'במחבת רחבה מחממים חמאה עד שמתחילה להזהיב. מוסיפים פטיות פרוסות ומאדים על אש גבוהה עד הזהבה.' },
      { title: 'יין ושמנת', body: 'מוסיפים שום, יוצקים יין ומאדים. כשהאלכוהול מתאדה מוסיפים שמנת ומבשלים 3 דקות עד הסמכה.' },
      { title: 'מאחדים', body: 'מעבירים את הפסטה לרוטב עם כף ממי הבישול, מערבבים עם פרמזן עד שהרוטב עוטף את הפסטה.' },
      { title: 'מגישים', body: 'מפזרים פטרוזיליה קצוצה, פלפל גרוס טרי ופרמזן נוסף. מגישים מיד.' },
    ],
  },
  {
    id: 'cupcakes',
    title: 'קאפקייקס וניל בקרם',
    subtitle: 'מאפה ילדים מושלם ליום הולדת',
    description: 'קאפקייקס וניל אווריריים ועדינים, עם כתר קרם חמאה רך בצבעים פסטליים. מוכנים בפחות מ-35 דקות — מושלם לכל אירוע.',
    palette: 'pink',
    category: 'bakery',
    cuisine: 'אמריקאית',
    time: 35, prepTime: 15, cookTime: 20, servings: 12, level: 'קל',
    favorite: false,
    notes: '',
    gallery: defaultGallery(),
    ingredients: [
      { qty: '180 גרם',  name: 'קמח לבן רגיל',         icon: 'grain' },
      { qty: '180 גרם',  name: 'סוכר לבן דק',           icon: 'sweet' },
      { qty: '180 גרם',  name: 'חמאה רכה',              icon: 'dairy' },
      { qty: '3 יח׳',    name: 'ביצים בטמפרטורת חדר',   icon: 'egg' },
      { qty: '1 כפית',   name: 'תמצית וניל איכותית',   icon: 'spice' },
      { qty: '1.5 כפיות', name: 'אבקת אפייה',           icon: 'chef' },
      { qty: '2 כפות',   name: 'חלב',                   icon: 'dairy' },
      { qty: '300 גרם',  name: 'אבקת סוכר לקרם',        icon: 'sweet' },
    ],
    steps: [
      { title: 'מקציפים', body: 'מקציפים חמאה וסוכר במיקסר כ-5 דקות עד תערובת בהירה ותפוחה.' },
      { title: 'מוסיפים ביצים', body: 'מוסיפים את הביצים אחת-אחת תוך הקצפה מתמשכת ולסיום את הוניל.' },
      { title: 'מקפלים יבשים', body: 'מקפלים בעדינות את הקמח עם אבקת האפייה ולבסוף את החלב לקבלת בלילה אחידה.' },
      { title: 'אופים', body: 'מחלקים ל-12 שקיות נייר בתבנית קאפקייקס, אופים ב-180°C כ-20–22 דקות עד שקיסם יוצא יבש.' },
      { title: 'מקשטים', body: 'מצננים לחלוטין, מקציפים קרם חמאה עם אבקת סוכר וצבע מאכל, מזלפים בקצה כוכב על הקאפקייקס המקוררים.' },
    ],
  },
];

Object.assign(window, { CATEGORIES, PALETTES, RECIPES, defaultGallery });
